sudo: required
services: 
  - docker

before_install:
  - docker build -t georgiosktistakis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true georgiosktistakis/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "ktistak-docker-app"
  env: "Ktistak-docker-app-env"
  bucket_name: "elasticbeanstalk-eu-north-1-546455860366"
  bucket_path: "ktistak-docker-app" 
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key: "$AWS_ACCESS_KEY"